version: "2.3"
services:
  web:
      container_name: merchant.api 
      image: moonlay/loyalti.merchant:testing
      ports:
        - 9090:9090
      depends_on:
        - redis
      volumes:
        - ./config.toml:/app/config.toml